---
##### seo #####
title: Justice & Mercy under the Trump Administration - CTA East Coast 2017
description: CTA East Coast Conference 2017. Join us in Baltimore, MD on October 20–21, 2017.
url:
twitter:
  username: CallToActionMD
logo:
social:
  name: Call to Action MD
  links:
    - https://twitter.com/CallToActionMD
    - https://www.facebook.com/CTAMD
webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234

##### etc #####
ga_analytics:
imgix:
  source: imgix.net
timezone: America/New_York

##### defaults #####

##### jekyll #####
permalink: pretty
exclude:
- "*.config"
- assets/src
- ".gitignore"
- Gulpfile.js
- node_modules
- package.json
- README*
- tools/
- webpack.config.js
gems:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll/imgix
